### ISSUE TITLE
Failing with Error "spawnSync /bin/sh ENOBUFS"

### ISSUE THREAD

**Issue by SanketPardeshi13** [dkershner6/jest-coverage-commenter-action#181]
Hi @dkershner6 , 

We are trying to post a coverage text summary on PR, but lately its failing continuesoly with error: spawnSync /bin/sh ENOBUFS.

Earlier it used to work without any issue, we used with following configuration.

name: Unit-tests
on:
  push:
    branches:
      - development
  pull_request:
    branches: [development, feature-**]
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # get all git history, commitlint needs full history
      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-npm-cache-
      - name: Install yarn dependencies
        run: |
          yarn install --frozen-lockfile
      - name: Run eslint
        run: yarn lint
      - name: Run tests with commenter
        if: ${{ github.event_name == 'pull_request' }}
        uses: dkershner6/jest-coverage-commenter-action@v1
        with:
          reporter: 'text-summary' # text summary provides summary of test coverage
          github_token: '${{ secrets.GITHUB_TOKEN }}'
          test_command: 'yarn test --coverageReporters'
      - name: Run tests
        if: ${{ github.event_name != 'pull_request' }}
        run: yarn test
      - name: Check commit message format
        if: ${{ github.event_name == 'pull_request' }}
       run: yarn commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose

**Comment by dkershner6** [comment]
Just updated this with everything updated, including Node 20, should be worth trying again.
